/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChatFriendIdRouteImport } from './routes/chat.$friendId'
import { Route as FriendFriendIdRouteImport } from './routes/friend.$friendId'
import { Route as GroupGroupIdRouteImport } from './routes/group.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFriendIdRoute = ChatFriendIdRouteImport.update({
  id: '/chat/$friendId',
  path: '/chat/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendFriendIdRoute = FriendFriendIdRouteImport.update({
  id: '/friend/$friendId',
  path: '/friend/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIdRoute = GroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/groups': typeof GroupsRoute
  '/profile': typeof ProfileRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friend/$friendId': typeof FriendFriendIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/groups': typeof GroupsRoute
  '/profile': typeof ProfileRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friend/$friendId': typeof FriendFriendIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/groups': typeof GroupsRoute
  '/profile': typeof ProfileRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friend/$friendId': typeof FriendFriendIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/friends'
    | '/groups'
    | '/profile'
    | '/chat/$friendId'
    | '/friend/$friendId'
    | '/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/friends'
    | '/groups'
    | '/profile'
    | '/chat/$friendId'
    | '/friend/$friendId'
    | '/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/friends'
    | '/groups'
    | '/profile'
    | '/chat/$friendId'
    | '/friend/$friendId'
    | '/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  GroupsRoute: typeof GroupsRoute
  ProfileRoute: typeof ProfileRoute
  ChatFriendIdRoute: typeof ChatFriendIdRoute
  FriendFriendIdRoute: typeof FriendFriendIdRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$friendId': {
      id: '/chat/$friendId'
      path: '/chat/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof ChatFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend/$friendId': {
      id: '/friend/$friendId'
      path: '/friend/$friendId'
      fullPath: '/friend/$friendId'
      preLoaderRoute: typeof FriendFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  GroupsRoute: GroupsRoute,
  ProfileRoute: ProfileRoute,
  ChatFriendIdRoute: ChatFriendIdRoute,
  FriendFriendIdRoute: FriendFriendIdRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
